# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_metadata.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity_metadata.proto',
  package='sync_pb',
  serialized_pb='\n\x15\x65ntity_metadata.proto\x12\x07sync_pb\"\xee\x01\n\x0e\x45ntityMetadata\x12\x17\n\x0f\x63lient_tag_hash\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x12\n\nis_deleted\x18\x03 \x01(\x08\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x12\x1d\n\x15\x61\x63ked_sequence_number\x18\x05 \x01(\x03\x12\x1a\n\x0eserver_version\x18\x06 \x01(\x03:\x02-1\x12\x15\n\rcreation_time\x18\x07 \x01(\x03\x12\x19\n\x11modification_time\x18\x08 \x01(\x03\x12\x16\n\x0especifics_hash\x18\t \x01(\tB\x04H\x03`\x01')




_ENTITYMETADATA = _descriptor.Descriptor(
  name='EntityMetadata',
  full_name='sync_pb.EntityMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_tag_hash', full_name='sync_pb.EntityMetadata.client_tag_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='sync_pb.EntityMetadata.server_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_deleted', full_name='sync_pb.EntityMetadata.is_deleted', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='sync_pb.EntityMetadata.sequence_number', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acked_sequence_number', full_name='sync_pb.EntityMetadata.acked_sequence_number', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_version', full_name='sync_pb.EntityMetadata.server_version', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='sync_pb.EntityMetadata.creation_time', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modification_time', full_name='sync_pb.EntityMetadata.modification_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specifics_hash', full_name='sync_pb.EntityMetadata.specifics_hash', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=273,
)

DESCRIPTOR.message_types_by_name['EntityMetadata'] = _ENTITYMETADATA

class EntityMetadata(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYMETADATA

  # @@protoc_insertion_point(class_scope:sync_pb.EntityMetadata)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
