# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synced_notification_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='synced_notification_specifics.proto',
  package='sync_pb',
  serialized_pb='\n#synced_notification_specifics.proto\x12\x07sync_pb\"\x1d\n\x1bSyncedNotificationSpecificsB\x04H\x03`\x01')




_SYNCEDNOTIFICATIONSPECIFICS = _descriptor.Descriptor(
  name='SyncedNotificationSpecifics',
  full_name='sync_pb.SyncedNotificationSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['SyncedNotificationSpecifics'] = _SYNCEDNOTIFICATIONSPECIFICS

class SyncedNotificationSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCEDNOTIFICATIONSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.SyncedNotificationSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
